name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing
on: [push]

jobs:
    steps:
    - name: Hello world action
        env: # Or as an environment variable
         hellow_secret: ${{ secrets.HELLOW }}
       
