name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing
on: [push]

jobs:
    build:
       
        steps:
           
            env:
                SAY_HELLOW: ${{secrets.SAY_HELLOW}}
          
            - run: echo "SAY_HELLOW = $SAY_HELLOW"
       
